# Generated by Django 5.0.6 on 2024-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=50)),
                ('text_text', models.CharField(max_length=1000)),
                ('text_modify_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
