# Generated by Django 5.0.6 on 2024-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django_NFSs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='.')),
            ],
        ),
        migrations.DeleteModel(
            name='TextFile',
        ),
    ]
