# Generated by Django 5.0.6 on 2024-07-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_django_NFSs', '0002_modelwithfilefield_delete_textfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithFileField',
        ),
    ]
